[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-bundle-env"
  # Specify the source directory explicitly so the plugin can find the env bundle
  [plugins.inputs]
  # 'source' is not a valid input for this plugin; use 'directories' instead
  directories = ["kesef-hevrati"]

[[plugins]]
  package = "netlify-plugin-use-env-in-runtime"

[[plugins]]
  package = "@netlify/plugin-lighthouse"
